### ISSUE TITLE
Bug when updating the data.

### ISSUE THREAD

**Issue by Danielhiversen** [wckd/python-yr#30]
Hello

Thanks for making this code!!

It seems that 'nextupdate' has changed to  '@nextrun'  in the API?

Running this twice gives an error: 
weather =  yr(coordinates=(63.4066631,10.4426724, 10), language_name='en')

ERROR:root:'nextupdate'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-30-6793c48a062f> in <module>()
----> 1 weather =  yr(coordinates=(63.4066631,10.4426724, 10), language_name='en')

/usr/local/lib/python3.4/dist-packages/yr/libyr.py in __init__(self, location_name, coordinates, location_xyz, forecast_link, language_name)
     75 
     76         self.connect = Connect(location=self.location)
---> 77         self.xml_source = self.connect.read()
     78         self.dictionary = self.xml2dict(self.xml_source)
     79         self.credit = self.language.dictionary['credit']

/usr/local/lib/python3.4/dist-packages/yr/utils.py in read(self)
    150             return weatherdata
    151         except Exception as e:
--> 152             raise YrException(e)
    153 
    154 class Cache(YrObject):

/usr/local/lib/python3.4/dist-packages/yr/utils.py in read(self)
    139             ))
    140             cache = Cache(self.location)
--> 141             if not cache.exists() or not cache.is_fresh():
    142                 logging.info('read online: {}'.format(self.location.url))
    143                 response = urllib.request.urlopen(self.location.url)

/usr/local/lib/python3.4/dist-packages/yr/utils.py in is_fresh(self)
    183     def is_fresh(self):
    184         logging.info('Now is {}'.format(datetime.datetime.now()))
--> 185         return datetime.datetime.now() <= self.valid_until_timestamp_from_file()
    186 
    187     def exists(self):

/usr/local/lib/python3.4/dist-packages/yr/utils.py in valid_until_timestamp_from_file(self)
    176         xmldata = self.load()
    177         d = xmltodict.parse(xmldata)
--> 178         next_update = d['weatherdata']['meta']['nextupdate']
    179         valid_until = datetime.datetime.strptime(next_update,"%Y-%m-%dT%H:%M:%S")
    180         logging.info('Cache is valid until {}'.format(valid_until))

KeyError: 'nextupdate'

**Comment by wckd** [comment]
I have checked the API-docs for yr.no, and I can't find anything mentioning "@nextrun", only 'nextupdate' in meta.
Example: http://www.yr.no/sted/Norge/Oslo/Oslo/Blindern/varsel.xml

**Comment by HugoShamrock** [comment]
fix created ...
pm
