### ISSUE TITLE
Logging to root

### ISSUE THREAD

**Issue by merry-bits** [wckd/python-yr#31]
All logging that I encountered so far goes to the root logger. This makes it difficult to change the logging behaviour of python-yr without changing all other logging as well.

Would it be possible for python-yr to use a separate named logger instead? For example something on the lines of `log = getLogger(__name__)`?

**Comment by wckd** [comment]
Merged in your PR, thank you for the contribution :-)

**Comment by merry-bits** [comment]
You are welcome! Thanks for accepting it.

2015-12-15 12:21 GMT+01:00 Alexander Hansen <notifications@github.com>:
