### ISSUE TITLE
Weather API from Yr.no deprecates URLs and adds HTTPS

### ISSUE THREAD

**Issue by wckd** [wckd/python-yr#34]
We need to add support for these new urls.
[https://www.slightfuture.com/devel/met-norway-api-endpoints](https://www.slightfuture.com/devel/met-norway-api-endpoints)

**Comment by knightsamar** [comment]
Hey @wkcd, what are the changes to the *http://www.yr.no/place* API endpoint that is used in Location class? Any idea? 

I can't seem to find any discussions in the mailing list regarding it nor does api.met.no/place (with or without HTTPS) work!

**Comment by knightsamar** [comment]
I have tried following URLs directly with curl:

https://api.met.no/place/Norge/Telemark/Skien/Skien/forecast.xml
https://www.api.met.no/place/Norge/Telemark/Skien/Skien/forecast.xml
http://api.met.no/place/Norge/Telemark/Skien/Skien/forecast.xml
http://www.api.met.no/place/Norge/Telemark/Skien/Skien/forecast.xml

But it ends up with a ``HTTP 404`` or ``Could not resolve host.``
