### ISSUE TITLE
Updating to Locationforecast/2.0?

### ISSUE THREAD

**Issue by Rory-Sullivan** [wckd/python-yr#41]
Hi there,

I'm just wondering if this project is being actively maintained and if so will you be updating it to use the new API launched by Yr? Yr recently launched their Locationforecast/2.0 API, more details on it here https://developer.yr.no/doc/locationforecast/HowTO/.

Thank you,
Rory

**Comment by wckd** [comment]
Hi Rory!
I just updated the code to use the new 2.0 API for locationforecast, and released the new version (1.4.7) on PyPI.
Do an upgrade and report back if something is breaking for you :)
