### ISSUE TITLE
No active exception to reraise

### ISSUE THREAD

**Issue by clemefr** [wckd/python-yr#42]
weather = Yr(location_xyz=(8.603894, 45.886332, 250)) # xyz for home
    now = weather.now(as_json=True)
    print(now)

This is not working anymore
result in an error "No active exception to reraise"

**Comment by fernandesGabriel** [comment]
I am facing the same issue

**Comment by wckd** [comment]
Hi @clemefr and @fernandesGabriel !

Met.no just released a new version of their API's that broke this library.
I have updated the library and released a new version on PyPI.
Do an upgrade and report back if this is still broken for you.

**Comment by fernandesGabriel** [comment]
Awesome @wckd. Worked like a charm.
